### ISSUE TITLE
(node:2805) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND 127.0.0.1:3000 127.0.0.1:3000:3000

### ISSUE THREAD

**Issue by oklas** [tedeh/jayson#163]
Tcp version crashes with error:

> (node:2805) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND 127.0.0.1:3000 127.0.0.1:3000:3000

Linux centos-2gb-nbg1-4 3.10.0-957.21.3.el7.x86_64
node -v v8.16.1

**Comment by tedeh** [comment]
ENOTFOUND means that the address is wrong.

**Comment by oklas** [comment]
Another clients access successfully to the same address.

**Comment by oklas** [comment]
The address `127.0.0.1` can not be wrong on any system.

**Comment by tedeh** [comment]
I have clarified use of a string option argument to the TLS and TCP client and removed URL parsing of string options in version `3.3.0` due to it not working.

In either case you need to pass an object argument such as `{host: '127.0.0.1', port: 3000}` unless you want to open a connection to a socket.
