### ISSUE TITLE
Tcp server does not respond after the first call

### ISSUE THREAD

**Issue by Lughino** [tedeh/jayson#55]
Use the tcp connection is a good way to have a two-way socket, with which you can go about taking an open connection.
After the fix to issue #41 was inserted "_.once()" on this [line](https://github.com/tedeh/jayson/blob/master/lib/utils.js#L106).

Is there a particular reason for this?
Removing "_.once()" the server responds to subsequent calls while keeping the same connection.

I noticed that the event is handled "error" of tcp socket. If this is not done the error arrives at global "uncaughtException" of process.
I added this to fix the problem:
```javascript
function getTcpListener(self, server) {
  return function(conn) {
    var options = self.options || {};

    conn.on('error', function() {
      conn.end();
    });
...
```
I opened an issue because I don't know if these are appropriate fix.
Great module, saved me a lot of time!

**Comment by tedeh** [comment]
The jayson server only emits one request because it naively assumes the jayson client is used (which closes the connection after one request so that it does not have to deal with buffering and response matching). I solved this in the attached commit. Now, errors will be emitted once (which causes the server to terminate the connection) and responses will be emitted indefinitely. Thanks for highlighting this!
