### ISSUE TITLE
Add support for methods that return promises

### ISSUE THREAD

**Issue by clark800** [tedeh/jayson#63]

**Comment by tedeh** [comment]
Should be handled using functions like [Bluebirds Promise.promisify](http://bluebirdjs.com/docs/api/promise.promisify.html) or another library/wrapper, or a separate extension that automatically wraps jaysons methods.

**Comment by clark800** [comment]
I should have clarified: I was referring to a situation where the user has a set of methods that return promises and they want to pass them to `jayson.Method`. If the user de-promisifies before passing to `jayson.Method`, they will lose the named parameters magic.

**Comment by tedeh** [comment]
I discourage the use of named parameters to jayson methods: it is fragile and prone to errors. The documentation does not state this clearly enough yet. I recommend that you give an option to your `jayson.Method` to collect all arguments, like this:

````javascript
var method = new jayson.Method({
    handler: function(args, done) {
      var total = sum(args);
      done(null, total);
    },
    collect: true // means "collect all JSON-RPC parameters in args"
});
````

Of course, doing this means that you can also "de-promisify" the actual handler before it is invoked by `jayson`: it will always be given two arguments (`args` and `done`)

**Comment by clark800** [comment]
> I discourage the use of named parameters to jayson methods: it is fragile and prone to errors.

Named parameters are part of the standard. Why are they fragile and prone to errors? We validate our method parameters with strict JSON schemas.

**Comment by tedeh** [comment]
I am talking about named parameters as the ability of `jayson` to fill parameters by parsing the actual JavaScript function signature and matching it against the parameters given in the JSON-RPC request. This is what I discourage (it is the only feature of jayson that I would consider "magic" which was the word used) There is of course no problem with passing an `Object` in the JSON-RPC request instead of an `Array` - something that the many tests show.

**Comment by clark800** [comment]
Ok I see. May I ask why that parsing is fragile?
